---
#ansible-playbook start.yaml --ask-become-pass
- name: Prepare master
  hosts: 127.0.0.1
  connection: local
  become: yes

  tasks:

    - name: Make sure pip is installed
      apt:
        name: python-pip
        state: present

    - name: Make sure jms is installed
      pip:
        name: jmespath
        state: present
