---
  - name: Prepare machines
    hosts: rpi
    become: yes

    tasks:

      - name: make sure pip3 is install
        apt:
          name: python3-pip
          state: present

      - name: ensure pexpect is installed in the playbook python
        pip:
          name: pexpect
          state: present
  
  - name: Install proxmox
    hosts: rpi
    become: yes

    tasks:

      - name: Get script and set as executable
        get_url:
         url: https://raw.githubusercontent.com/pimox/pimox7/442393fd99d214527ecb066de3160108ae32fc66/RPiOS64-IA-Install.sh
         dest: /home/pi/RPiOS64-IA-Install.sh
         mode: 0755

      - name: Correct start of file
        replace:
          path: /home/pi/RPiOS64-IA-Install.sh
          regexp: '# !/bin/bash'
          replace: '#!/bin/bash'

      - name: Run script
        ansible.builtin.expect:
          command: "./RPiOS64-IA-Install.sh"
          responses:
            'Enter new hostname e.g. RPi4-01-PVE' : "RPiX-PVE-X0{{ play_hosts.index(inventory_hostname)+1 }}"
            "Enter new static IP and NETMASK e.g. 192.168.0.100\/24" : "192.168.1.10{{ play_hosts.index(inventory_hostname)+1 }}\/24"
            'gateway' : 'y'
            'New password' : "raspberry"
            'Retype new password' : "raspberry"
          timeout: 3600
        ignore_errors: true

      #   register: runcmd
      #   tags: runcmd

      # - debug: msg="{{runcmd.stdout}}"

  # - name: Create file with hostname
  #   hosts: rpi
  #   become: yes

  #   tasks:
  #     - name: Run script
  #       ansible.builtin.expect:
  #         command: "./script.sh"
  #         responses:
  #           'enter hostname' : "RPiX-PVE-X0{{ play_hosts.index(inventory_hostname)+1 }}"
  #       ignore_errors: true
  #       register: result

      - name: (reboot) Wait for server to restart
        wait_for_connection:
          delay: 120

      
